//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyPC_AutoMusic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyPC_AutoMusic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加乐谱文件 的本地化字符串。
        /// </summary>
        public static string List_Btn_Add {
            get {
                return ResourceManager.GetString("List_Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选择的乐谱 的本地化字符串。
        /// </summary>
        public static string List_Btn_Delete {
            get {
                return ResourceManager.GetString("List_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件夹批量导入 的本地化字符串。
        /// </summary>
        public static string List_Btn_ImportFolder {
            get {
                return ResourceManager.GetString("List_Btn_ImportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string List_Btn_Search {
            get {
                return ResourceManager.GetString("List_Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入筛选词 的本地化字符串。
        /// </summary>
        public static string List_FilterTips {
            get {
                return ResourceManager.GetString("List_FilterTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放列表 的本地化字符串。
        /// </summary>
        public static string List_Header_SheetsList {
            get {
                return ResourceManager.GetString("List_Header_SheetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱导入失败,请检查乐谱格式是否正确 的本地化字符串。
        /// </summary>
        public static string List_ImportFailure {
            get {
                return ResourceManager.GetString("List_ImportFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下是导入失败的文件： 的本地化字符串。
        /// </summary>
        public static string List_ImportFailureList {
            get {
                return ResourceManager.GetString("List_ImportFailureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (目前仅支持导入未加密Json乐谱) 的本地化字符串。
        /// </summary>
        public static string List_ImportFailureTips {
            get {
                return ResourceManager.GetString("List_ImportFailureTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱导入中，请耐心等待... 的本地化字符串。
        /// </summary>
        public static string List_ImportingFiles {
            get {
                return ResourceManager.GetString("List_ImportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导入{0}首乐谱 的本地化字符串。
        /// </summary>
        public static string List_ImportingInBackground {
            get {
                return ResourceManager.GetString("List_ImportingInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}首乐谱导入成功,{1}首乐谱导入失败 的本地化字符串。
        /// </summary>
        public static string List_ImportResult {
            get {
                return ResourceManager.GetString("List_ImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        public static string List_ImportSuccessfully {
            get {
                return ResourceManager.GetString("List_ImportSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择乐谱文件 的本地化字符串。
        /// </summary>
        public static string List_ImportWindowTitle {
            get {
                return ResourceManager.GetString("List_ImportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有选择乐谱 的本地化字符串。
        /// </summary>
        public static string List_NullDelete {
            get {
                return ResourceManager.GetString("List_NullDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文件 的本地化字符串。
        /// </summary>
        public static string List_TextFile {
            get {
                return ResourceManager.GetString("List_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演奏 的本地化字符串。
        /// </summary>
        public static string Main_Play {
            get {
                return ResourceManager.GetString("Main_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱 的本地化字符串。
        /// </summary>
        public static string Main_Sheets {
            get {
                return ResourceManager.GetString("Main_Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPAM 播放器 的本地化字符串。
        /// </summary>
        public static string Main_WindowTitle {
            get {
                return ResourceManager.GetString("Main_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并连续相同按键 的本地化字符串。
        /// </summary>
        public static string Options_CombineKeys {
            get {
                return ResourceManager.GetString("Options_CombineKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Options_Confirm {
            get {
                return ResourceManager.GetString("Options_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义背景图像 的本地化字符串。
        /// </summary>
        public static string Options_CustomBackground {
            get {
                return ResourceManager.GetString("Options_CustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色模式 的本地化字符串。
        /// </summary>
        public static string Options_DarkMode {
            get {
                return ResourceManager.GetString("Options_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源地址 的本地化字符串。
        /// </summary>
        public static string Options_GitHub {
            get {
                return ResourceManager.GetString("Options_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Options_Header_About {
            get {
                return ResourceManager.GetString("Options_Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Options_Header_Appearance {
            get {
                return ResourceManager.GetString("Options_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用SkyStudio键位映射 的本地化字符串。
        /// </summary>
        public static string Options_KeyMapper {
            get {
                return ResourceManager.GetString("Options_KeyMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件读取失败，所有设置项已重置为默认值 的本地化字符串。
        /// </summary>
        public static string Options_ReadConfigFailure {
            get {
                return ResourceManager.GetString("Options_ReadConfigFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从设置文件读取路径失败 的本地化字符串。
        /// </summary>
        public static string Options_ReadPathFailure {
            get {
                return ResourceManager.GetString("Options_ReadPathFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色跟随系统 的本地化字符串。
        /// </summary>
        public static string Options_ThemeColorFollowSystem {
            get {
                return ResourceManager.GetString("Options_ThemeColorFollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分乐谱与此功能不兼容，若演奏过程出现意外缺音吞音，请关闭此功能 的本地化字符串。
        /// </summary>
        public static string Options_Tips_CombineKeys {
            get {
                return ResourceManager.GetString("Options_Tips_CombineKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到背景图片，请将bg.jpg(或bg.png)与程序放在同一目录下 的本地化字符串。
        /// </summary>
        public static string Options_Tips_MissBackgroundFile {
            get {
                return ResourceManager.GetString("Options_Tips_MissBackgroundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置项将在程序重启后生效 的本地化字符串。
        /// </summary>
        public static string Options_Tips_RestartApp {
            get {
                return ResourceManager.GetString("Options_Tips_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是第一首音乐 的本地化字符串。
        /// </summary>
        public static string Play_AlreadyFirstMusic {
            get {
                return ResourceManager.GetString("Play_AlreadyFirstMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最后一首音乐 的本地化字符串。
        /// </summary>
        public static string Play_AlreadyLastMusic {
            get {
                return ResourceManager.GetString("Play_AlreadyLastMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换下一首 的本地化字符串。
        /// </summary>
        public static string Play_Btn_NextMusic {
            get {
                return ResourceManager.GetString("Play_Btn_NextMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换上一首 的本地化字符串。
        /// </summary>
        public static string Play_Btn_PreviousMusic {
            get {
                return ResourceManager.GetString("Play_Btn_PreviousMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Play_Info_Author {
            get {
                return ResourceManager.GetString("Play_Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱详情 的本地化字符串。
        /// </summary>
        public static string Play_Info_Header {
            get {
                return ResourceManager.GetString("Play_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲名 的本地化字符串。
        /// </summary>
        public static string Play_Info_Name {
            get {
                return ResourceManager.GetString("Play_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调性 的本地化字符串。
        /// </summary>
        public static string Play_Info_PitchLevel {
            get {
                return ResourceManager.GetString("Play_Info_PitchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改编者 的本地化字符串。
        /// </summary>
        public static string Play_Info_TranscribedBy {
            get {
                return ResourceManager.GetString("Play_Info_TranscribedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有添加乐谱 的本地化字符串。
        /// </summary>
        public static string Play_MissSheet {
            get {
                return ResourceManager.GetString("Play_MissSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播完暂停 的本地化字符串。
        /// </summary>
        public static string Play_Mode1 {
            get {
                return ResourceManager.GetString("Play_Mode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单曲循环 的本地化字符串。
        /// </summary>
        public static string Play_Mode2 {
            get {
                return ResourceManager.GetString("Play_Mode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序播放 的本地化字符串。
        /// </summary>
        public static string Play_Mode3 {
            get {
                return ResourceManager.GetString("Play_Mode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Play_Pause {
            get {
                return ResourceManager.GetString("Play_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        public static string Play_Start {
            get {
                return ResourceManager.GetString("Play_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序遇到一些问题，该操作已终止，请联系程序开发者反馈此问题 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
